# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - aks-tf-az/*
      - azure-pipelines.yml

stages:
- stage: validate
  jobs:
    - job: tf_validate
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-tf-az/dev'
            backendServiceArm: 'Azure subscription 1(68e4c6a4-43e4-4dca-a352-db3694c871c4)'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'tfdevbackend2026sandy'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-tf-az/dev'

- stage: Dev_deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
    - job: terraform_apply_dev
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-tf-az/dev'
            backendServiceArm: 'Azure subscription 1(68e4c6a4-43e4-4dca-a352-db3694c871c4)'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'tfdevbackend2026sandy'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-tf-az/dev'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'Azure subscription 1(68e4c6a4-43e4-4dca-a352-db3694c871c4)'

- stage: stage_deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
    - job: terraform_apply_stage
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-tf-az/staging'
            backendServiceArm: 'Azure subscription 1(68e4c6a4-43e4-4dca-a352-db3694c871c4)'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'tfstagebackend2026sandy'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'stage.terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-tf-az/staging'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'Azure subscription 1(68e4c6a4-43e4-4dca-a352-db3694c871c4)'